### ISSUE TITLE
Mocked interface doesn't return the value already set with every

### ISSUE THREAD

**Issue by mustafaozhan** [lupuuss/Mokkery#16]
During solving migration issues another issue come up, previously passing test start failing. I narrow down the issue, and it looks like mocked interface doesn't return the value already set with every. Maybe it is again some behavioral difference of Mokkery but couldn't be sure.

You can see the code piece in the [PR](https://github.com/Oztechan/CCC/pull/3608/files)

Let me know if anything is needed from my end!

**Comment by lupuuss** [comment]
Mocked objects don't utilize configured answers in `every`/`verify` blocks; they return *default*/*empty* values instead. This is why you can't use returned values as mentioned in #11. 

I don't believe this is a behavioral change, and Mockative does not support it either. The primary difference is that Mokkery allows multiple invocations in a single `verify` (without accessing returned values), whereas Mockative allows only a single mock call in the `verify`/`every` block. This single call [throws special exception](https://github.com/mockative/mockative/blob/c2926e4807a8423196f7dad9ed635fa0c9e8c0e3/mockative/src/commonMain/kotlin/io/mockative/Mockable.kt#L126) and `verify` block is not executed further. In short, the problem always existed, but due to the way Mockative works, it wasn't visible.

Mockk, which also allows multiple calls in the verify block, shows similar behavior.

**Comment by mustafaozhan** [comment]
@lupuuss I am sorry my bad I am updating the title it is not an object, it is an interface. I am updating the title and the definition

**Comment by lupuuss** [comment]
I know it's about interface. The first paragraph is about Mokkery's mocks in general (I've slightly updated my answer). Mock invocations inside `verify`/`every` block returns *empty* value e.g. `0` for `Int`, `""` for `String`, null for complex types. Therefore, accessing those values is meaningless. I would suggest this code:
```kotlin
verify {
    appStorage.sessionCount 
    analyticsManager.setUserProperty(UserProperty.SessionCount("1"))
}
```
It checks if `sessionCount` and `analyticsManager.setUserProperty` with `UserProperty.SessionCount("1")` were invoked at least once in any order. You can change `VerifyMode` to make this check more strict.


This fragment
> This single call [throws special exception](https://github.com/mockative/mockative/blob/c2926e4807a8423196f7dad9ed635fa0c9e8c0e3/mockative/src/commonMain/kotlin/io/mockative/Mockable.kt#L126) and verify block is not executed further

was about Mockative. In the second paragraph, I tried to explain why the `verify` block using Mockative was incorrect, why it still passed, and why it results in a runtime exception with Mokkery.

**Comment by mustafaozhan** [comment]
Ohh I got it now the part, that was my mistake
> Mock invocations inside verify/every block return empty values e.g. 0 for Int, "" for String, null for complex types
thank you for clarifying.

Also the part with mockative, yes indeed it explains why it was not failing previously. Anyways thank you for the explanations now I confirm that everything works as expected.
