### ISSUE TITLE
Not able to verify objects by their content

### ISSUE THREAD

**Issue by mikolajefento** [lupuuss/Mokkery#22]
Hello!
I've found an issue with verifying the objects when the contents are the same but instances are not.
Here is the error message:

```
Calls to the same method with failing matchers:
  ByteArrayParser(1).doNothing(id = UUID@fcb4004, value = [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33])
    [-] id:
       expect: UUID@8c11eee
       actual: UUID@fcb4004
    [-] value:
       expect: [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33]
       actual: [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33]

```

As one can see the contents of byte array are the same. Also I am using the `any()` matcher so it should not matter if the contents are the same at the first place.

The minimal reproducible example is attached.
[multiplatform-library-template.zip](https://github.com/user-attachments/files/16142320/multiplatform-library-template.zip)
Tested on Mac with apple chip and on windows

**Comment by lupuuss** [comment]
It's expected behavior. All literal arguments are checked by `equals`. It seems that both `ByteArray` and `UUID` have default `equals` (by reference).  For arrays it's a known behavior and mokkery provides a matcher [contentEq](https://mokkery.dev/api_reference/mokkery-runtime/dev.mokkery.matcher.collections/content-eq.html). For UUID, override `equals` or use custom matcher e.g. [matching](https://mokkery.dev/api_reference/mokkery-runtime/dev.mokkery.matcher/matching.html).

**Comment by mikolajefento** [comment]
Ok, makes sense. I've tried verifying with custom matcher and it works fine now. Thank you for quick response!
