### ISSUE TITLE
Provide callback mechanism when calls are made

### ISSUE THREAD

**Issue by dalewking** [lupuuss/Mokkery#34]
I would like to see a global call back mechanism to monitor calls to mocks and possibly even modify the behavior.

One use for this would be for logging. In complex cases where the SUT is interacting with multiple mocks it is helpful to debug to see what parameters were passed to the mock and what the mock is returning via logging.

It would also provide a way to handle my request in #20

As I see it at the minimum such a callback interface could look like:
```
    interface MockCallback {
        fun called(scope: FunctionScope, result: Result<Any>) : Result<Any>
        suspend fun calledSuspend(scope: FunctionScope, result: Result<Any>) : Result<Any> = called(scope, result)
    }
```

This lets you:
- know when a mock is called and can log it
- override the return value
- add additional behavior such as blocking the return from the function

**Comment by lupuuss** [comment]
So it's more of an interceptor mechanism.

Technically, implementing the ability to intercept mock calls is not very complicated on its own. However, doing it in the right place can be challenging and requires careful consideration.

The bigger issue is registering that interceptor globally in tests, because there's no single entry point for doing this in Kotlin Multiplatform. In JVM projects, `ServiceLoader`s are available and sufficient, but for other targets, it's not as straightforward. There are some tricks, like using the [EagerInitialization](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/-eager-initialization/) annotation, but it's marked as deprecated. On the other hand, `Ktor` uses this trick, so maybe it won't be removed without a replacement.

In general, I should be able to implement intercepting on its own, but initial release might not contain global registering.

**Comment by lupuuss** [comment]
[Added in 2.5.0](https://github.com/lupuuss/Mokkery/releases/tag/v2.5.0)
