### ISSUE TITLE
Cannot invoke "dev.mokkery.interceptor.MokkeryCallInterceptor.intercept(dev.mokkery.interceptor.MokkeryBlockingCallScope)"

### ISSUE THREAD

**Issue by steveyak** [lupuuss/Mokkery#64]
I am using the allopen plugin to mock ViewModel classes directly without the need for interfaces. The issue arises when the ViewModel calls a method within its init {} block. The error occurs right after the method is invoked in the init block: 

_**Cannot invoke "dev.mokkery.interceptor.MokkeryCallInterceptor.intercept(dev.mokkery.interceptor.MokkeryBlockingCallScope)" because the return value of "dev.mokkery.internal.MokkeryInstance.get_mokkeryInterceptor()" is null
java.lang.NullPointerException: Cannot invoke "dev.mokkery.interceptor.MokkeryCallInterceptor.intercept(dev.mokkery.interceptor.MokkeryBlockingCallScope)" because the return value of "dev.mokkery.internal.MokkeryInstance.get_mokkeryInterceptor()" is null**_

**My init block is structured like this:**

```
init {
    observeDemoModeChanges()
}

private fun observeDemoModeChanges() {
    viewModelScope.launch {
        demoDataService.isDemoMode.collect {
            refreshData(true)
        }
    }
}

```
**The mock setup is as follows:**

`viewModel = mock<ServiceViewModel>(MockMode.autoUnit) {}`

I used autoUnit to automatically mock the private method observeDemoModeChanges. The issue arises because observeDemoModeChanges is executed, and then the execution stops when it calls refreshData(true), which should also be mocked since it has no return value (Unit)

**Comment by lupuuss** [comment]
Hi! There are two things I want to address in your issue here:
1. You've mentioned private methods mocking - it's not really possible with Mokkery. It's only possible to mock public and overridable members.
2. The all-open plugin is required for Mokkery to inherit from the type you want to mock. The issue arises because you are using an overridable member in your constructor. [This is not considered safe, as the inheritor might access its state there.](https://stackoverflow.com/a/15327631) This is exactly what's happening in your case - when creating mocks, Mokkery adds an `interceptor` field to the mock, and calling `refreshData(true)` during construction causes the `interceptor` to be accessed before it's properly initialized.

The only thing I can do here is suggest avoiding the use of overridable methods in the constructor, as the mock is not ready yet.
